---
- hosts: all
  gather_facts: no
  vars_files: debian-vars-file.yaml
  roles:
# Initialization
    - python
    - upgrade-packages
    - install-packages
    - download-dotfiles-repo
# Security
  # - remove-sudo
  # - config-ufw
  # - config-fail2ban
# Services
  # - install-openmediavault
  # - install-nextcloud
  # - install-jellyfin
