- name: 'Making sure python is installed'
  ansible.builtin.raw: >
    command -v python ||
    (test -e /etc/debian_version && apt-get update && apt-get install -y python) ||
    (test -e /etc/arch-release && pacman -Syy python --noconfirm)
  changed_when: false
