- name: 'Creating ./rasbian-cfg/ssh dir'
  ansible.builtin.file:
    path: ./rasbian-cfg/ssh/
    state: directory

- name: 'Creating SSH keypair in host machine'
  community.crypto.openssh_keypair:
    path: ./rasbian-cfg/ssh/ssh-key

- name: 'Creating root/.ssh dir'
  ansible.builtin.file:
    path: ./rasbian-cfg/root/root/.ssh/
    state: directory

- name: 'Adding public SSH key to root/.ssh/authorized_keys'
  ansible.builtin.copy:
    src: ./rasbian-cfg/ssh/ssh-key.pub
    dest: ./rasbian-cfg/root/root/.ssh/authorized_keys
